version: '3.5'

services:
  hop-server:
    image: apache/hop:2.3.0
    container_name: hop-server
    environment:
      HOP_OPTIONS: "-Xmx4096m -Dfile.encoding=UTF8"
      HOP_SERVER_PORT: 8182
      #HOP_RUN_CONFIG: /opt/config
      #HOP_CONFIG_FOLDER: /opt/config
      #HOP_PROJECT_NAME: ""
      #HOP_PROJECT_CONFIG_FILE_NAME: ""
      #HOP_ENVIRONMENT_NAME: ""
    volumes:
      # - ./config:/opt/config
      #- ./projetos:/opt/projetos/
    ports:
      - "8182:8182"
    restart: on-failure
    networks:
      - hop
      - postgres-prd

networks:
  hop:
    external: true
    name: hop
  postgres-prd:
    external: true
    name: postgres-prd
